CREATE TABLE IF NOT EXISTS guildmembers (
    `id` INTEGER PRIMARY KEY AUTOINCREMENT,
    `guild_slug` VARCHAR(255) NOT NULL,
    `character_id` INT UNIQUE NOT NULL,
    `Rank` VARCHAR(255) NOT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (guild_slug) REFERENCES guilds (slug) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (character_id) REFERENCES characters (id) ON DELETE CASCADE ON UPDATE CASCADE
);