CREATE TABLE IF NOT EXISTS characters (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `unique_id_number` INT UNSIGNED NOT NULL,
    `firstname` VARCHAR(255) NOT NULL,
    `lastname` VARCHAR(255) NOT NULL,
    `faction` VARCHAR(255) DEFAULT NULL,
    `species` VARCHAR(255) DEFAULT NULL,
    `slug` VARCHAR(255) NOT NULL,
    `short_title` VARCHAR(255) DEFAULT NULL,
    `full_title` VARCHAR(255) DEFAULT NULL,
    `age` INT UNSIGNED DEFAULT NULL,
    `gender` VARCHAR(255) DEFAULT NULL,
    `pronouns` VARCHAR(255) DEFAULT NULL,
    `height` FLOAT DEFAULT NULL,
    `weight` FLOAT DEFAULT NULL,
    `birthplace` VARCHAR(255) DEFAULT NULL,
    `residence` VARCHAR(255) DEFAULT NULL,
    `about` TEXT DEFAULT NULL,
    `history` TEXT DEFAULT NULL,
    `created_at` TIMESTAMP DEFAULT NOW(),
    `updated_at` TIMESTAMP DEFAULT NOW(),
    PRIMARY KEY (id),
    UNIQUE KEY (unique_id_number),
    UNIQUE KEY (slug)
);